name: llamadart_chat_example
description: Chat interface example using llamadart
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.10.7
  flutter: ^3.38.0

dependencies:
  flutter:
    sdk: flutter
  llamadart:
    path: ../..  # Use local version
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  file_picker: ^10.3.10
  path: ^1.9.0
  dio: ^5.9.0
  path_provider: ^2.1.5
  google_fonts: ^8.0.0
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.2
  json_rpc_2: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  test: ^1.26.3

  ffi: any
  http: any
flutter:
  uses-material-design: true
